# .github/workflows/deploy.yml

name: Deploy Eleventy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      
      - name: GitHub Pages - Configure
        uses: actions/configure-pages@v5
        
      - name: Install pre-requirements
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CMS_URL: ${{ secrets.CMS_URL }}
          COLLECTION_NAME: NeonpastelCat
          STATIC_TOKEN: ${{ secrets.STATIC_TOKEN }}
          OUTPUT_FILENAME: src/_data/{{collectionName}}.json
        
      - name: GitHub Pages - Upload dist/ artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

      - name: Github Pages - Deploy
        id: deployment
        uses: actions/deploy-pages@v1
