# .github/workflows/directus.yml
name: Update data from Directus webhook

on:
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      
      - name: Install directus-to-data
        run: yarn add directus-to-data

      - name: Fetch data
        run: npx directus-to-data
        env:
          CMS_URL: ${{ secrets.CMS_URL }}
          COLLECTION_NAME: NeonpastelCat
          STATIC_TOKEN: ${{ secrets.STATIC_TOKEN }}
          OUTPUT_FILENAME: src/_data/{{collectionName}}.json
      
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'src/_data/*'
          default_author: github_actions
          message: 'CMS update (${{ github.event.repository.updated_at}})'

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: update-data
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit
